#!/usr/bin/env python
"""Build a standalone macOS binary of usbscope with PyInstaller.

The result is a single Mach-O executable that bundles the Python interpreter and
Rich, so it runs on a Mac without Python, uv or a virtualenv. Everything the
script produces lands in ``dist/``:

    usbscope-<version>-macos-<arch>          the binary
    usbscope-<version>-macos-<arch>.tar.gz   same binary, mode preserved
    SHA256SUMS                               checksums of both

Usage
-----
    uv run python scripts/build_binary.py                    # build + verify
    uv run python scripts/build_binary.py --arch x86_64      # other architecture
    uv run python scripts/build_binary.py --no-sign          # skip ad-hoc signing

The binary is signed *ad hoc* (``codesign -s -``), which is enough to run on the
machine that built it. It is neither Developer-ID signed nor notarised, so a
download is still stopped by Gatekeeper - see docs/index.md, "Prebuilt binary".
"""

from __future__ import annotations

import argparse
import hashlib
import platform
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"
BUILD = ROOT / "build"
SPEC = ROOT / "build" / "pyinstaller"
ENTRYPOINT = BUILD / "pyinstaller_entrypoint.py"
ENTRYPOINT_SOURCE = '''"""Generated by scripts/build_binary.py - PyInstaller entry point."""

from usbscope.cli import main

raise SystemExit(main())
'''


def _run(argv: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run a command in the repository root and return the completed process."""
    result = subprocess.run(argv, cwd=ROOT, capture_output=True, text=True, check=False)
    if check and result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise SystemExit(f"{' '.join(argv[:3])}… failed:\n{detail}")
    return result


def build_parser() -> argparse.ArgumentParser:
    """Create the argument parser."""
    default_arch = platform.machine()
    parser = argparse.ArgumentParser(description="Build a standalone macOS binary of usbscope.")
    parser.add_argument(
        "--arch", default=default_arch, help=f"target architecture (default {default_arch})"
    )
    parser.add_argument("--name", default="usbscope", help="binary name")
    parser.add_argument("--python", default=f"{sys.version_info.major}.{sys.version_info.minor}")
    parser.add_argument("--no-sign", action="store_true", help="skip the ad-hoc codesign step")
    parser.add_argument(
        "--keep-build", action="store_true", help="keep the PyInstaller work directory"
    )
    return parser


def _version() -> str:
    from usbscope import __version__

    return __version__


def run_pyinstaller(name: str, arch: str, python_version: str) -> Path:
    """Run PyInstaller and return the path of the produced binary."""
    ENTRYPOINT.parent.mkdir(parents=True, exist_ok=True)
    ENTRYPOINT.write_text(ENTRYPOINT_SOURCE, encoding="utf-8")
    argv = [
        "uv",
        "run",
        "--no-dev",
        f"--python={python_version}",
        "--with",
        "pyinstaller",
        "pyinstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--log-level",
        "WARN",
        "--name",
        name,
        "--distpath",
        str(DIST),
        "--workpath",
        str(SPEC),
        "--specpath",
        str(BUILD),
        "--osx-bundle-identifier",
        "com.zopyx.usbscope",
        "--exclude-module",
        "pytest",
        "--exclude-module",
        "ty",
        "--exclude-module",
        "ruff",
        "--exclude-module",
        "mypy",
    ]
    if sys.platform == "darwin":
        argv += ["--target-architecture", arch]
    argv.append(str(ENTRYPOINT))
    print(f"building {name} ({arch}, Python {python_version}) …", flush=True)
    result = _run(argv, check=False)
    if result.returncode != 0 or not (binary := DIST / name).exists():
        detail = (result.stderr or result.stdout).strip().splitlines()[-15:]
        raise SystemExit("PyInstaller failed:\n" + "\n".join(detail))
    return binary


def sign(binary: Path) -> str:
    """Ad-hoc sign the binary (enough to run locally, not for distribution)."""
    if shutil.which("codesign") is None:
        return "codesign not found — skipped"
    _run(
        [
            "codesign",
            "--force",
            "--sign",
            "-",
            "--identifier",
            "com.zopyx.usbscope",
            str(binary),
        ]
    )
    verify = _run(["codesign", "--verify", "--verbose=2", str(binary)], check=False)
    return (
        "ad-hoc signed"
        if verify.returncode == 0
        else f"signature check failed: {verify.stderr.strip()}"
    )


def verify(binary: Path) -> list[str]:
    """Run the built binary and check that it really works."""
    checks: list[str] = []
    version = _run([str(binary), "--version"])
    checks.append(f"--version → {version.stdout.strip()}")

    payload = _run([str(binary), "--json"])
    import json

    try:
        data = json.loads(payload.stdout)
    except ValueError as exc:
        raise SystemExit(f"built binary returned invalid JSON: {exc}") from None
    checks.append(
        f"--json → schema {data['schema_version']}, "
        f"{data['summary']['ports']} ports, {data['summary']['devices']} devices, "
        f"{len(data['buses'])} buses"
    )

    rendered = _run([str(binary), "ports", "--no-color"])
    if "Port" not in rendered.stdout or "State" not in rendered.stdout:
        raise SystemExit("built binary did not render the port table")
    checks.append(f"ports view → {len(rendered.stdout.splitlines())} lines rendered")

    kind = _run(["file", "-b", str(binary)]).stdout.strip()
    checks.append(f"file → {kind}")
    return checks


def checksum(binary: Path) -> str:
    """Return the SHA-256 of a file."""
    digest = hashlib.sha256()
    with binary.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def package(binary: Path, arch: str) -> tuple[Path, Path]:
    """Create the versioned bare binary and the tarball (mode preserving)."""
    version = _version()
    stem = f"{binary.name}-{version}-macos-{arch}"
    bare = DIST / stem
    shutil.copy2(binary, bare)
    tarball = DIST / f"{stem}.tar.gz"
    with tarfile.open(tarball, "w:gz") as archive:
        archive.add(bare, arcname=binary.name)
    sums = DIST / "SHA256SUMS"
    lines = [f"{checksum(path)}  {path.name}" for path in (bare, tarball)]
    sums.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return bare, tarball


def main(argv: list[str] | None = None) -> int:
    """Build, sign, verify and package the binary; returns the exit code."""
    args = build_parser().parse_args(argv)
    DIST.mkdir(exist_ok=True)
    binary = run_pyinstaller(args.name, args.arch, args.python)

    signature = "skipped (--no-sign)" if args.no_sign else sign(binary)
    checks = verify(binary)
    bare, tarball = package(binary, args.arch)

    size_mb = bare.stat().st_size / 1024 / 1024
    print(f"\n{signature}")
    for check in checks:
        print(f"  {check}")
    print(f"\nartifacts in {DIST.relative_to(ROOT)}/")
    for path in (bare, tarball, DIST / "SHA256SUMS"):
        print(f"  {path.name:44} {path.stat().st_size / 1024:8.1f} KiB")
    print(f"  binary size {size_mb:.1f} MiB")

    if not args.keep_build:
        shutil.rmtree(SPEC, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
