#!/usr/bin/env python
"""Build ``usbscope.app`` — the native macOS app as a double clickable bundle.

PyInstaller collects Python, Rich and PyObjC into a ``.app`` with an Info.plist and
the app icon, the script then fills in the bundle metadata, signs it ad hoc,
launches the bundled binary once (in ``--snapshot`` mode, so nothing appears on
screen) to prove the bundle works, and writes a styled DMG plus SHA-256 sums:

    dist/usbscope.app                     (icon: assets/icon/usbscope.icns)
    dist/usbscope-<version>-macos-<arch>.dmg
    dist/SHA256SUMS-app

Usage
-----
    uv run python scripts/build_app.py              # build + verify + DMG
    uv run python scripts/build_app.py --no-dmg     # .app only
    uv run python scripts/build_app.py --no-sign    # skip codesign
    uv run python scripts/build_app.py --no-icon    # without the app icon

The DMG step delegates to ``scripts/make_dmg.py`` (staging folder with an
``/Applications`` symlink, Finder layout, mount verification). Like the CLI binary
this is an ad-hoc signature, not a Developer ID one, so a browser download is still
quarantined by Gatekeeper (see docs/distribution.md).
"""

from __future__ import annotations

import argparse
import hashlib
import platform
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"
SPEC = ROOT / "build" / "pyinstaller-app"
ENTRYPOINT = ROOT / "build" / "pyinstaller_app_entrypoint.py"
ENTRYPOINT_SOURCE = '''"""Generated by scripts/build_app.py - PyInstaller entry point."""

from usbscope.macapp.launch import main

raise SystemExit(main())
'''
BUNDLE_ID = "com.zopyx.usbscope"


def _version() -> str:
    from usbscope import __version__

    return __version__


def _run(argv: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(argv, cwd=ROOT, capture_output=True, text=True, check=False)
    if check and result.returncode != 0:
        raise SystemExit(
            f"{' '.join(argv[:3])}… failed:\n{(result.stderr or result.stdout).strip()}"
        )
    return result


def build_parser() -> argparse.ArgumentParser:
    """Create the argument parser."""
    parser = argparse.ArgumentParser(description="Build usbscope.app with PyInstaller.")
    parser.add_argument("--arch", default=platform.machine(), help="target architecture")
    parser.add_argument("--name", default="usbscope", help="app name")
    parser.add_argument(
        "--python",
        default=f"{sys.version_info.major}.{sys.version_info.minor}",
        help="Python version",
    )
    parser.add_argument("--no-sign", action="store_true", help="skip the ad-hoc codesign step")
    parser.add_argument("--no-dmg", action="store_true", help="skip the DMG")
    parser.add_argument(
        "--icon",
        type=Path,
        default=ROOT / "assets" / "icon" / "usbscope.icns",
        help="app icon (.icns); regenerate it with `make icon`",
    )
    parser.add_argument("--no-icon", action="store_true", help="build without an app icon")
    return parser


def run_pyinstaller(name: str, arch: str, python_version: str, icon: Path | None = None) -> Path:
    """Run PyInstaller and return the path of the produced .app bundle."""
    ENTRYPOINT.parent.mkdir(parents=True, exist_ok=True)
    ENTRYPOINT.write_text(ENTRYPOINT_SOURCE, encoding="utf-8")
    if icon is not None and not icon.exists():
        raise SystemExit(f"icon not found: {icon} (run: make icon)")
    icon = icon if icon is not None and icon.exists() else None
    if icon is not None:
        print(f"icon: {icon.relative_to(ROOT)}", flush=True)
    print(f"building {name}.app ({arch}, Python {python_version}) …", flush=True)
    result = _run(
        [
            "uv",
            "run",
            "--no-dev",
            "--extra",
            "macapp",
            f"--python={python_version}",
            "--with",
            "pyinstaller",
            "pyinstaller",
            "--noconfirm",
            "--clean",
            "--windowed",
            "--log-level",
            "WARN",
            "--name",
            name,
            "--distpath",
            str(DIST),
            "--workpath",
            str(SPEC),
            "--specpath",
            str(ROOT / "build"),
            "--osx-bundle-identifier",
            BUNDLE_ID,
            "--target-architecture",
            arch,
            "--icon",
            str(icon),
            "--exclude-module",
            "pytest",
            "--exclude-module",
            "ty",
            "--exclude-module",
            "ruff",
            str(ENTRYPOINT),
        ],
        check=False,
    )
    bundle = DIST / f"{name}.app"
    if result.returncode != 0 or not bundle.exists():
        tail = (result.stderr or result.stdout).strip().splitlines()[-15:]
        raise SystemExit("PyInstaller failed:\n" + "\n".join(tail))
    return bundle


def patch_info_plist(bundle: Path, name: str, icon_name: str | None = None) -> dict[str, object]:
    """Fill in the bundle metadata macOS shows in the Finder."""
    plist_path = bundle / "Contents" / "Info.plist"
    with plist_path.open("rb") as handle:
        plist = plistlib.load(handle)
    if icon_name:
        plist["CFBundleIconFile"] = icon_name
    plist.update(
        {
            "CFBundleName": name,
            "CFBundleDisplayName": name,
            "CFBundleIdentifier": BUNDLE_ID,
            "CFBundleShortVersionString": _version(),
            "CFBundleVersion": _version(),
            "CFBundleExecutable": name,
            "LSMinimumSystemVersion": "13.0",
            "NSHighResolutionCapable": True,
            "NSHumanReadableCopyright": "MIT licensed",
            "LSApplicationCategoryType": "public.app-category.utilities",
            # App Store Connect asks about export compliance on every upload; saying it
            # here keeps the question out of the submission flow
            "ITSAppUsesNonExemptEncryption": False,
        }
    )
    with plist_path.open("wb") as handle:
        plistlib.dump(plist, handle, sort_keys=False)
    return plist


def sign(bundle: Path) -> str:
    """Ad-hoc sign the bundle (deep, because of the embedded frameworks)."""
    if shutil.which("codesign") is None:
        return "codesign not found — skipped"
    _run(
        [
            "codesign",
            "--force",
            "--deep",
            "--sign",
            "-",
            "--identifier",
            BUNDLE_ID,
            str(bundle),
        ]
    )
    verify = _run(["codesign", "--verify", "--verbose=2", str(bundle)], check=False)
    return (
        "ad-hoc signed"
        if verify.returncode == 0
        else f"signature check failed: {verify.stderr.strip()}"
    )


def verify(bundle: Path) -> list[str]:
    """Run the bundled executable in snapshot mode: proves the bundle works."""
    executable = bundle / "Contents" / "MacOS" / bundle.stem
    if not executable.exists():
        raise SystemExit(f"bundle has no executable at {executable}")
    target = Path("/tmp") / f"{bundle.stem}-bundle-check.png"
    result = _run([str(executable), "--snapshot", str(target), "--view", "ports"], check=False)
    if result.returncode != 0 or not target.exists() or target.stat().st_size < 10_000:
        raise SystemExit(
            f"bundled app failed the snapshot check (exit {result.returncode}):\n"
            f"{(result.stderr or result.stdout).strip()[:600]}"
        )
    checks = [
        f"launched {executable.name} --snapshot → {target.stat().st_size // 1024} KiB PNG",
        f"version {_run([str(executable), '--version']).stdout.strip()}",
    ]
    plist = plistlib.loads((bundle / "Contents" / "Info.plist").read_bytes())
    checks.append(
        f"Info.plist: {plist['CFBundleIdentifier']} {plist.get('CFBundleShortVersionString')} "
        f"(min macOS {plist.get('LSMinimumSystemVersion')})"
    )
    return checks


def checksum(path: Path) -> str:
    """Return the SHA-256 of a file."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def make_dmg(bundle: Path, arch: str, *, volume_name: str) -> tuple[Path, Path]:
    """Create the styled DMG (``scripts/make_dmg.py``) and the sums file.

    ``make_dmg.py`` stages the app plus an ``/Applications`` symlink, applies the
    Finder layout (icon view, positions, background) best effort and verifies the
    mounted result; the checksum file keeps the release convention used here.
    """
    dmg = DIST / f"{bundle.stem}-{_version()}-macos-{arch}.dmg"
    dmg.unlink(missing_ok=True)
    result = _run(
        [
            sys.executable,
            str(ROOT / "scripts" / "make_dmg.py"),
            str(bundle),
            str(dmg),
            "--volume-name",
            volume_name,
        ],
        check=False,
    )
    if result.returncode != 0 or not dmg.exists():
        tail = (result.stderr or result.stdout).strip().splitlines()[-10:]
        raise SystemExit("make_dmg.py failed:\n" + "\n".join(tail))
    for line in (result.stdout or "").strip().splitlines():
        print(f"  {line}")
    sums = DIST / "SHA256SUMS-app"
    sums.write_text(f"{checksum(dmg)}  {dmg.name}\n", encoding="utf-8")
    return dmg, sums


def main(argv: list[str] | None = None) -> int:
    """Build, sign, verify and package the app; returns the exit code."""
    args = build_parser().parse_args(argv)
    DIST.mkdir(exist_ok=True)
    icon = None if args.no_icon else args.icon
    bundle = run_pyinstaller(args.name, args.arch, args.python, icon=icon)
    plist = patch_info_plist(bundle, args.name, icon.name if icon is not None else None)
    signature = "skipped (--no-sign)" if args.no_sign else sign(bundle)
    checks = verify(bundle)

    print(f"\n{signature}")
    for check in checks:
        print(f"  {check}")
    size = sum(f.stat().st_size for f in bundle.rglob("*") if f.is_file()) / 1024 / 1024
    print(f"\n{DIST.relative_to(ROOT)}/{bundle.name}  ({size:.1f} MiB, {plist['CFBundleName']})")
    if not args.no_dmg:
        dmg, sums = make_dmg(bundle, args.arch, volume_name=args.name)
        print(f"  {dmg.name}  ({dmg.stat().st_size / 1024 / 1024:.1f} MiB)")
        print(f"  {sums.name}")
    shutil.rmtree(SPEC, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
